//WARNING: This file is AUTOMATICALLY generated. Changes will be OVERWRITTEN!
#include <fstream>

#include <catch2/catch.h>

#include <challenge/advent_of_code/main.h>

namespace tul{
namespace test{
namespace aoc{

TEST_CASE( "aoc/2019_02_1", "[aoc], [aoc/2019]" ){
	auto solver = challenge::aoc::load(2019, 2);
	auto answer = [&solver](std::istream& in){
		return solver->part_1(in).get_answer();
	};

	SECTION( "hidden case I" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_1");
		REQUIRE( answer(in) == "4484226" );
	}

	SECTION( "hidden case II" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_2");
		REQUIRE( answer(in) == "4330636" );
	}

	SECTION( "hidden case III" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_3");
		REQUIRE( answer(in) == "4138658" );
	}

	SECTION( "hidden case IV" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_4");
		REQUIRE( answer(in) == "3224742" );
	}

	SECTION( "hidden case V" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_5");
		REQUIRE( answer(in) == "3895705" );
	}

	SECTION( "hidden case VI" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_6");
		REQUIRE( answer(in) == "5098658" );
	}

	SECTION( "hidden case VII" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_7");
		REQUIRE( answer(in) == "4714701" );
	}

	SECTION( "hidden case VIII" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_8");
		REQUIRE( answer(in) == "7210630" );
	}

	SECTION( "hidden case IX" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_9");
		REQUIRE( answer(in) == "5534943" );
	}

	SECTION( "hidden case X" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_10");
		REQUIRE( answer(in) == "4138687" );
	}

	SECTION( "hidden case XI" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_11");
		REQUIRE( answer(in) == "9706670" );
	}
}

TEST_CASE( "aoc/2019_02_2", "[aoc], [aoc/2019]" ){
	auto solver = challenge::aoc::load(2019, 2);
	auto answer = [&solver](std::istream& in){
		return solver->part_2(in).get_answer();
	};

	SECTION( "hidden case I" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_1");
		REQUIRE( answer(in) == "5696" );
	}

	SECTION( "hidden case II" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_2");
		REQUIRE( answer(in) == "6086" );
	}

	SECTION( "hidden case III" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_3");
		REQUIRE( answer(in) == "7264" );
	}

	SECTION( "hidden case IV" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_4");
		REQUIRE( answer(in) == "7960" );
	}

	SECTION( "hidden case V" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_5");
		REQUIRE( answer(in) == "6417" );
	}

	SECTION( "hidden case VI" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_6");
		REQUIRE( answer(in) == "5064" );
	}

	SECTION( "hidden case VII" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_7");
		REQUIRE( answer(in) == "5121" );
	}

	SECTION( "hidden case VIII" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_8");
		REQUIRE( answer(in) == "3892" );
	}

	SECTION( "hidden case IX" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_9");
		REQUIRE( answer(in) == "7603" );
	}

	SECTION( "hidden case X" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_10");
		REQUIRE( answer(in) == "6635" );
	}

	SECTION( "hidden case XI" ){
		std::ifstream in("test/advent_of_code/2019/02_hidden_11");
		REQUIRE( answer(in) == "2552" );
	}
}

}
}
}
