//WARNING: This file is AUTOMATICALLY generated. Changes will be OVERWRITTEN!
#include <fstream>

#include <catch2/catch.h>

#include <challenge/advent_of_code/main.h>

namespace tul{
namespace test{
namespace aoc{

TEST_CASE( "aoc/2019_05_1", "[aoc], [aoc/2019]" ){
	auto solver = challenge::aoc::load(2019, 5);
	auto answer = [&solver](std::istream& in){
		return solver->part_1(in).get_answer();
	};

	SECTION( "hidden case I" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_1");
		REQUIRE( answer(in) == "9219874" );
	}

	SECTION( "hidden case II" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_2");
		REQUIRE( answer(in) == "15097178" );
	}

	SECTION( "hidden case III" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_3");
		REQUIRE( answer(in) == "13933662" );
	}

	SECTION( "hidden case IV" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_4");
		REQUIRE( answer(in) == "15259545" );
	}

	SECTION( "hidden case V" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_5");
		REQUIRE( answer(in) == "7839346" );
	}

	SECTION( "hidden case VI" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_6");
		REQUIRE( answer(in) == "15386262" );
	}

	SECTION( "hidden case VII" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_7");
		REQUIRE( answer(in) == "9025675" );
	}
}

TEST_CASE( "aoc/2019_05_2", "[aoc], [aoc/2019]" ){
	auto solver = challenge::aoc::load(2019, 5);
	auto answer = [&solver](std::istream& in){
		return solver->part_2(in).get_answer();
	};

	SECTION( "hidden case I" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_1");
		REQUIRE( answer(in) == "5893654" );
	}

	SECTION( "hidden case II" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_2");
		REQUIRE( answer(in) == "1558663" );
	}

	SECTION( "hidden case III" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_3");
		REQUIRE( answer(in) == "2369720" );
	}

	SECTION( "hidden case IV" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_4");
		REQUIRE( answer(in) == "7616021" );
	}

	SECTION( "hidden case V" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_5");
		REQUIRE( answer(in) == "447803" );
	}

	SECTION( "hidden case VI" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_6");
		REQUIRE( answer(in) == "10376124" );
	}

	SECTION( "hidden case VII" ){
		std::ifstream in("test/advent_of_code/2019/05_hidden_7");
		REQUIRE( answer(in) == "11981754" );
	}
}

}
}
}
