//WARNING: This file is AUTOMATICALLY generated. Changes will be OVERWRITTEN!
#ifndef hash_guard_e698e4be9eb02ec7_537f6034eaf723d1_b7a79bf87deeb274_0406b214e1507863
#define hash_guard_e698e4be9eb02ec7_537f6034eaf723d1_b7a79bf87deeb274_0406b214e1507863

#include <memory>

#include <spdlog/spdlog.h>

#include <master_h/macro/logger_fwd.h>

#include "../solver.h"

namespace tul{
namespace challenge{
namespace aoc{
namespace y2019{

TUL_MACRO_PREFIX__LOGGER__LOGGER_DECL

void init_logger();

std::unique_ptr<Solver> load(int day);

}
}
}
}

#endif // hash_guard_e698e4be9eb02ec7_537f6034eaf723d1_b7a79bf87deeb274_0406b214e1507863
