//WARNING: This file is AUTOMATICALLY generated. Changes will be OVERWRITTEN!
#ifndef hash_guard_ae0cc10911467499_750003e0ba6bf7e6_2a640b8a89749de1_91a610f86399e455
#define hash_guard_ae0cc10911467499_750003e0ba6bf7e6_2a640b8a89749de1_91a610f86399e455

#include <memory>

#include "../solver.h"

namespace tul{
namespace challenge{
namespace aoc{
namespace y2019{

std::unique_ptr<Solver> load(int day);

}
}
}
}

#endif // hash_guard_ae0cc10911467499_750003e0ba6bf7e6_2a640b8a89749de1_91a610f86399e455
