//WARNING: This file is AUTOMATICALLY generated. Changes will be OVERWRITTEN!
#ifndef hash_guard_a8ba73015de70e50_943396b058fad7fa_42912bc82ef066df_21a166248db33aec
#define hash_guard_a8ba73015de70e50_943396b058fad7fa_42912bc82ef066df_21a166248db33aec

#include <memory>

#include "../solver.h"

namespace tul{
namespace challenge{
namespace aoc{
namespace y2016{

std::unique_ptr<Solver> load(int day);

}
}
}
}

#endif // hash_guard_a8ba73015de70e50_943396b058fad7fa_42912bc82ef066df_21a166248db33aec
