//WARNING: This file is AUTOMATICALLY generated. Changes will be OVERWRITTEN!
#ifndef hash_guard_888fdd364d0de0d4_578d4c5e24cb2263_94ee92d5bc9ab4ac_52274c7a1619d8e9
#define hash_guard_888fdd364d0de0d4_578d4c5e24cb2263_94ee92d5bc9ab4ac_52274c7a1619d8e9

#include <memory>

#include "../solver.h"

namespace tul{
namespace challenge{
namespace aoc{
namespace y2017{

std::unique_ptr<Solver> load(int day);

}
}
}
}

#endif // hash_guard_888fdd364d0de0d4_578d4c5e24cb2263_94ee92d5bc9ab4ac_52274c7a1619d8e9
